name: Build & Test

on: push

env:
  CACHE: /tmp/cache

jobs:
  build:
    name: Build Dependencies
    runs-on: ubuntu-16.04
    env:
      LD_LIBRARY_PATH: $CACHE/openssl/lib:$LD_LIBRARY_PATH

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lookup Cache
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ${{ env.CACHE }}
        key: ${{ hashFiles('**/.requirements') }}

    - name: Add to Path
      run: echo "::add-path::$CACHE/openssl/bin:$CACHE/openresty/nginx/sbin:$CACHE/openresty/bin:$CACHE/luarocks/bin:$PATH"

    - name: Install packages
      run: sudo apt-get install -y libyaml-dev

    - name: Execute
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
          dep_version() {
              grep $1 .requirements | sed -e 's/.*=//' | tr -d '\n'
          }

          OPENRESTY=$(dep_version RESTY_VERSION)
          LUAROCKS=$(dep_version RESTY_LUAROCKS_VERSION)
          OPENSSL=$(dep_version RESTY_OPENSSL_VERSION)
          GO_PLUGINSERVER=$(dep_version KONG_GO_PLUGINSERVER_VERSION)

          DOWNLOAD_ROOT=$GITHUB_WORKSPACE/download-root
          BUILD_TOOLS_DOWNLOAD=$DOWNLOAD_ROOT/kong-build-tools
          GO_PLUGINSERVER_DOWNLOAD=$DOWNLOAD_ROOT/go-pluginserver

          INSTALL_ROOT=$CACHE
          mkdir -p $INSTALL_ROOT

          KONG_NGINX_MODULE_BRANCH=${KONG_NGINX_MODULE_BRANCH:=master}

          # conditional next/master
          KONG_BUILD_TOOLS_BRANCH=${KONG_BUILD_TOOLS_BRANCH:=master}

          git clone -b $KONG_BUILD_TOOLS_BRANCH \
            https://github.com/Kong/kong-build-tools.git
          export PATH=$PWD/kong-build-tools/openresty-build-tools:$PATH
          echo $PATH

          git clone -b $GO_PLUGINSERVER \
            https://github.com/Kong/go-pluginserver
          export PATH=$PWD/go-pluginserver:$PATH
          echo $PATH

          pushd go-pluginserver
            go get ./...
            make
          popd
          mv go-pluginserver/go-pluginserver $INSTALL_ROOT/go-pluginserver

          NUM_THREADS=$(( $(nproc) * 2 + 1 ))
          echo "Building with $NUM_THREADS threads..."

          kong-ngx-build \
              --work $DOWNLOAD_ROOT \
              --prefix $INSTALL_ROOT \
              --openresty $OPENRESTY \
              --kong-nginx-module $KONG_NGINX_MODULE_BRANCH \
              --luarocks $LUAROCKS \
              --openssl $OPENSSL \
              -j $NUM_THREADS

          make dev

  test:
    name: Lint & Unit
    runs-on: ubuntu-16.04
    needs: build

    env:
      LD_LIBRARY_PATH: $CACHE/openssl/lib:$LD_LIBRARY_PATH
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: postgres

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: kong
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lookup Cache
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ${{ env.CACHE }}
        key: ${{ hashFiles('**/.requirements') }}

    - name: Add to Path
      run: echo "::add-path::$CACHE/openssl/bin:$CACHE/openresty/nginx/sbin:$CACHE/openresty/bin:$CACHE/luarocks/bin:$PATH"

    # TODO need a better way to install (or cache) this
    - name: Install packages
      run: sudo apt-get install -y libyaml-dev

    - name: Execute
      run: |
        eval `luarocks path`
        make dev
        make lint
        make test

  integration-postgres:
    name: Integration - Postgres
    runs-on: ubuntu-16.04
    needs: build

    env:
      LD_LIBRARY_PATH: $CACHE/openssl/lib:$LD_LIBRARY_PATH
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: postgres

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: kong
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lookup Cache
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ${{ env.CACHE }}
        key: ${{ hashFiles('**/.requirements') }}

    - name: Add to Path
      run: echo "::add-path::$CACHE/openssl/bin:$CACHE/openresty/nginx/sbin:$CACHE/openresty/bin:$CACHE/luarocks/bin:$PATH"

    # TODO need a better way to install (or cache) this
    - name: Install packages
      run: sudo apt-get install -y libyaml-dev

    - name: Execute
      run: |
        eval `luarocks path`
        make dev
        KONG_TEST_DATABASE=postgres TEST_SUITE=integration .ci/run_tests.sh

  integration-dbless:
    name: Integration - DB-less
    runs-on: ubuntu-16.04
    needs: build

    env:
      LD_LIBRARY_PATH: $CACHE/openssl/lib:$LD_LIBRARY_PATH
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: postgres

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: kong
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lookup Cache
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ${{ env.CACHE }}
        key: ${{ hashFiles('**/.requirements') }}

    - name: Add to Path
      run: echo "::add-path::$CACHE/openssl/bin:$CACHE/openresty/nginx/sbin:$CACHE/openresty/bin:$CACHE/luarocks/bin:$PATH"

    # TODO need a better way to install (or cache) this
    - name: Install packages
      run: sudo apt-get install -y libyaml-dev

    - name: Execute
      run: |
        eval `luarocks path`
        make dev
        KONG_TEST_DATABASE=off TEST_SUITE=dbless .ci/run_tests.sh

  plugins-postgres:
    name: Plugins - Postgres
    runs-on: ubuntu-16.04
    needs: build

    env:
      LD_LIBRARY_PATH: $CACHE/openssl/lib:$LD_LIBRARY_PATH
      KONG_TEST_PG_DATABASE: kong
      KONG_TEST_PG_USER: postgres

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: kong
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lookup Cache
      uses: actions/cache@v1
      id: cache-deps
      with:
        path: ${{ env.CACHE }}
        key: ${{ hashFiles('**/.requirements') }}

    - name: Add to Path
      run: echo "::add-path::$CACHE/openssl/bin:$CACHE/openresty/nginx/sbin:$CACHE/openresty/bin:$CACHE/luarocks/bin:$PATH"

    # TODO need a better way to install (or cache) this
    - name: Install packages
      run: sudo apt-get install -y libyaml-dev

    - name: Execute
      run: |
        eval `luarocks path`
        make dev
        KONG_TEST_DATABASE=postgres TEST_SUITE=plugins .ci/run_tests.sh
